networks:

  t3lls_gate--app_net:
    external: true

  t3lls_gate--api_net:
    external: true

  t3lls_gate--adminer_net:
    external: true

  api-tools--db_net:
    driver: bridge

  db-tools--adminer_net:
    driver: bridge

secrets:
  db_password:
    file: .secrets/db_password

services:

  njs-tools:
    build:
      context: ./njs-tools/next-app
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 3006:3000
    networks:
      - t3lls_gate--app_net
    env_file:
      - ./njs-tools/.env
    stop_grace_period: 0s

  njs-tools-dev:
    container_name: tools-njs-tools-dev
    build:
      context: ./njs-tools/next-app
      dockerfile: dev.Dockerfile
    restart: always
    ports:
      - 3007:3000
    networks:
      - t3lls_gate--app_net
    volumes:
      - ./njs-tools/next-app/src:/app/src
      - ./njs-tools/next-app/public:/app/public
    env_file:
      - ./njs-tools/.env
    stop_grace_period: 0s

  api-tools:
    build:
      context: ./api-tools
      dockerfile: dev.Dockerfile
    restart: always
    networks: # internal port 8080
      - t3lls_gate--api_net
      - api-tools--db_net
    volumes:
      - ./api-tools/app:/code/app
    secrets:
      - db_password

  db-tools:
    build:
      context: ./db-tools
      dockerfile: Dockerfile
    restart: unless-stopped
    networks: # internal port 5432
      - api-tools--db_net
      - db-tools--adminer_net
    volumes:
      - ./db-tools/data:/var/lib/postgresql/data        # Add data mount
      - ./db-tools/schema:/var/lib/postgresql/schema    # Add schema mount
      - ./db-tools/exports:/var/lib/postgresql/exports  # Add exports mount
    environment:
      POSTGRES_USER: manualuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: tools
    command: ["-c", "shared_preload_libraries=uuid-ossp"]
    secrets:
      - db_password

  db-tools-adminer:
    container_name: tools-db-tools-adminer
    image: adminer
    restart: always
    networks: # internal port 8080
      - t3lls_gate--adminer_net
      - db-tools--adminer_net